name: payment-tests

on:
  pull_request:
    paths:
      - 'payments/**'
      - '.github/workflows/payment-tests.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
